name: Version Check
description: Checks whether or not the provided version already exists as a tag on the repository
author: DrizlyInc/DVX

inputs:

  version:
    required: false
    description: The version to check
    default: ''

  version_file:
    required: false
    description: Path to a file containg the version to check
    default: ''

  username:
    required: true
    description: Username for authenticating to GitHub API (github.actor)

  token:
    required: true
    description: Token for authenticating to GitHub API (github.token)

outputs:

  new-version:
    description: "'true' if the given version does not exist as a tag, otherwise 'false'"

  version:
    description: "The version that was checked, either from input or from reading the version_file"

runs:
  using: docker
  image: docker://ghcr.io/drizlyinc/version-check-action:v0.3.0