name: Release

on: push

jobs:

  check-if-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.parse-version.outputs.version }}
      new-version: ${{ steps.check-version.outputs.new-version }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Parse Version From action.yml
        id: parse-version
        run: echo "::set-output name=version::$(cat action.yml | tail -1 | cut -d ':' -f4)"

      - uses: DrizlyInc/version-check-action@v0.2.0
        id: check-version
        with:
          version: ${{ steps.parse-version.outputs.version }}


  release:
    needs: check-if-release
    if: ${{ github.ref == 'refs/heads/main' && needs.check-if-release.outputs.new-version == 'true' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Publish Image
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ github.token }}
          containerRegistry: true
          tag: |
            latest
            ${{ needs.check-if-release.outputs.version }}
            ${{ github.sha }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.check-if-release.outputs.version }}